# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExelbidSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExelbidSample
  
  # Facebook
  pod 'FBAudienceNetwork'
  
  # Digital Turbine
  pod 'Fyber_Marketplace_SDK'
  
  # Pangle
  pod 'Ads-Global'
  
  # Applovin
  pod 'AppLovinSDK'

end
